# Build settings

markdown: redcarpet
permalink: pretty
baseurl: /site
exclude: ['README.md']

port: 3000

sass:
  sass_dir: assets/css
  style: :nested

# Site settings
#-----------------------
# Header

title: Ewout Hasken
description: History // Creative // Politics

#--------------------

# About
about-title: Versatile and engaged

about-text: I am Ewout, an energetic young historian and political scientist. I am a keen researcher who likes to untangle complex historical events and their impact on current affairs. I want to fathom past human actions and behaviour, and understand how these actions have shaped and influenced the world around us. Besides being an avid researcher I am an engaged student who contributes not only to the academic community but society at large. I have been part of numerous committees and have been a board member of different associations. My experiences, academic or in working capacity, have made me resourceful, stress resistant and versatile.


#----------------------

# Interests


#----------------------

# Skills

skills-title: Pulvinar Finibus Ante

skills-text: I am a versatile researcher with a variety of different skills ranging from policy making to research. Since I have read history and political science, I am trained in the research traditions of both humanities and social sciences. I have experience with qualitative and quantitative research, as well as statistical analyses. I am also trained in interpretative research methods and critical source analysis. This combination of academic skills enables me to use an interdisciplinary approach to research. In the past I have for example examined the influence of framing as a sociological concept on memories of war. Besides these academic skills I am experienced in policy processes.

#----------------------

# CV

cv-title: Academic and professional

cv-text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean convallis felis sit amet ante finibus pulvinar. Donec et faucibus lorem.

cv: 'assets/pdf/CV_Ewout_Hasken.pdf'

#----------------------

# Contact

contact-title: let's get in touch

contact-text: Use the form below and I will get back to you.

#----------------------
